//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpawnTraffic.AppCmd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpawnTraffic.AppCmd.Resources.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Brand: .
        /// </summary>
        internal static string AddSkaterInputBrand {
            get {
                return ResourceManager.GetString("AddSkaterInputBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name: .
        /// </summary>
        internal static string AddSkaterInputName {
            get {
                return ResourceManager.GetString("AddSkaterInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------&gt;Add Skater&lt;--------.
        /// </summary>
        internal static string AddSkaterTitle {
            get {
                return ResourceManager.GetString("AddSkaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC &gt; Exit.
        /// </summary>
        internal static string EscapeExitInfo {
            get {
                return ResourceManager.GetString("EscapeExitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: {0} - Name: {1} - Brand: {2}.
        /// </summary>
        internal static string ListSkaterResult {
            get {
                return ResourceManager.GetString("ListSkaterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------&gt;List Skaters&lt;--------.
        /// </summary>
        internal static string ListSkaterTitle {
            get {
                return ResourceManager.GetString("ListSkaterTitle", resourceCulture);
            }
        }
    }
}
