USE SpawnTraffic
GO

IF (NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES 
				 WHERE TABLE_SCHEMA = 'app' 
				AND  TABLE_NAME = 'Log'))
BEGIN
	CREATE TABLE app.Log (
		[Id] INT IDENTITY (1, 1) NOT NULL,
		[Date] DATETIMEOFFSET(7) NULL,
		[MessageType] INT NULL,
		[Message] NVARCHAR(500),
		[Created] [DATETIMEOFFSET] NULL CONSTRAINT [DF_Log_Created] DEFAULT (SYSDATETIMEOFFSET()),
		[Modified] [DATETIMEOFFSET]
		CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED ([Id] ASC)
	);
END
GO
